# Generated by Django 4.2.4 on 2023-09-27 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumno', '0005_alter_alumnotable_correo_electronico'),
        ('rutina', '0003_remove_rutina_duracion_estimada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_reserva', models.DateTimeField()),
                ('estado_reserva', models.CharField(max_length=50)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.alumnotable')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutina.rutina')),
            ],
        ),
    ]
