# Generated by Django 4.2.4 on 2023-10-02 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profesor', '0003_profesor_correo_electronico_and_more'),
        ('rutina', '0003_remove_rutina_duracion_estimada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesor.profesor')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutina.rutina')),
            ],
        ),
    ]
