# Generated by Django 4.2.4 on 2023-10-03 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horarios',
            name='dia_semana',
        ),
        migrations.AddField(
            model_name='horarios',
            name='dias_semana',
            field=models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miércoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sábado', 'Sábado'), ('domingo', 'Domingo')], default=50, max_length=50),
            preserve_default=False,
        ),
    ]
