# Generated by Django 4.2.4 on 2023-09-26 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('nivel_dificultad', models.CharField(max_length=50)),
                ('duracion_estimada', models.IntegerField()),
            ],
        ),
    ]
