# Generated by Django 4.2.4 on 2023-09-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0002_alter_rutina_nivel_dificultad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutina',
            name='duracion_estimada',
        ),
        migrations.AddField(
            model_name='rutina',
            name='descanso_entre_series',
            field=models.CharField(choices=[('5 min', '5 Minutos'), ('3 min', '3 Minutos'), ('2 min', '2 Minutos'), ('1 min', '1 Minuto')], default=100, max_length=50),
            preserve_default=False,
        ),
    ]
