# Generated by Django 4.2.4 on 2023-09-23 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='alumno',
            new_name='alumnoTable',
        ),
    ]
