# Generated by Django 4.2.4 on 2023-09-26 01:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0002_rename_alumno_alumnotable'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnotable',
            name='correo_electronico',
            field=models.EmailField(default=100, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumnotable',
            name='fecha_de_nacimiento',
            field=models.DateField(default=datetime.datetime(2023, 9, 26, 1, 2, 24, 197437, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
