# Generated by Django 4.2.4 on 2023-09-26 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0003_alumnotable_correo_electronico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnotable',
            name='correo_electronico',
            field=models.EmailField(max_length=254, verbose_name='sin_correo@ejemplo.com'),
        ),
    ]
