# Generated by Django 4.2.4 on 2023-09-26 01:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0002_profesor_apellido_profesor_disponibilidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='correo_electronico',
            field=models.EmailField(default='sin_correo@ejemplo.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesor',
            name='fecha_de_nacimiento',
            field=models.DateField(default=datetime.datetime(2023, 9, 26, 1, 10, 57, 928259, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
